### ISSUE TITLE
Unable to compile esp32 flite 

### ISSUE THREAD

**Issue by jalakamkiranadspl** [alkhimey/esp32-flite#2]
Hey @alkhimey , Thanks for the repo. I am trying to build the script but not able to as it is failing to find the header file some how. 

`../main/main.c:18:10: fatal error: flite.h: No such file or directory
 #include "flite.h"
          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

I am using esp if v4.4, can you please point out the mistake I am making.
Thank you.

**Comment by alkhimey** [comment]
Hi, sorry for the late response.
I will try to build myself with v4.4 over the weekend.

**Comment by jalakamkiranadspl** [comment]
@alkhimey Thanks, That would be great.

**Comment by alkhimey** [comment]
I pushed a fix to master. I verified that it builds with v4.3 but I believe it will work with v4.4 as well. The issue was that esp-idf updated the build system to use CMake.
I did not flash and run it on hardware though.

**Comment by jalakamkiranadspl** [comment]
Thanks, @alkhimey I am going to test out the hardware ASAP and close this issue.
